# Run from mipnerf360 root so `python -m train` can find train.py
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${SCRIPT_DIR}/.." || exit 1

# Sparse KITTI data generated by keeping every 4th frame from the dense data.
# Override DATA_DIR to train on another sparse sequence.
SPARSE_KITTI_ROOT="${SPARSE_KITTI_ROOT:-/home/ubuntu/final_project/data/kitti/kitti_select_static_5seq_sparse_every4}"
DATA_DIR="${DATA_DIR:-${SPARSE_KITTI_ROOT}/KITTISeq02_2011_10_03_drive_0034_sync_llffdtu_s2749_e2929_densegt}"
CHECKPOINT_DIR="${CHECKPOINT_DIR:-${DATA_DIR}/logs/checkpoints-sparse-every4-7.5w-mse}"

python -m train \
  --gin_configs=configs/360.gin \
  --gin_bindings="Config.max_steps = 75000" \
  --gin_bindings="Config.sample_every = 1" \
  --gin_bindings="Config.data_dir = '${DATA_DIR}'" \
  --gin_bindings="Config.compute_disp_metrics = True" \
  --gin_bindings="Config.depth_loss_type = 'mse'" \
  --gin_bindings="Config.checkpoint_dir = '${CHECKPOINT_DIR}'" \
  --logtostderr
